### ISSUE TITLE
parcial Completen esto con el nombre de su grupo

### ISSUE THREAD

**Issue by franco-creator** [pdep-lunes-tarde/2024-objetos-recuperatorio-1-franco-creator#1]
buenas profe ahi entrego el parcial

Juan Fernandes @juanFdS

**Comment by JuanFdS** [comment]
## Parte A
### Punto 1
⚠️ La túnica épica no es un ""subtipo"" de la común como para ser su subclase, sino que ambas son ""subtipos"" de túnicas.
⚠️ Estaría bueno tener un mensaje más expresivo para el n° de letras del nombre del mago, que es algo que se reutiliza en varios puntos del código.
Fuera de eso, está bien ✅
### Punto 2
❌ El desafío no indica ""cuántos puntos se quiere robar"", sino que la energía robada depende de la categoría del mago vencido y de sus puntos actuales.
⚠️ Se rompe el encapsulamiento del mago al solicitarle su categoría en lugar de que el mago sea responsable de hacer ese ""pasamanos"". Esto implica que estamos ""obligando"" a que el mago tenga una categoría como parte de su interfaz, lo cual probablemente complique la parte B.
⚠️ No se expone una manera para cambiar la categoría del mago, a pesar de que se indica que debería poderse.
## Parte B
### Punto 1
✅
### Punto 2
❌ En esta implementación un mago no puede desafiar a un gremio, cuando es algo que se encuentra en los bullet points.
⚠️ No hay un uso correcto del polimorfismo al discriminar ""desde afuera"" entre magos y gremios. Debería enviarse el mismo mensaje y delegar en los objetos la resolución acorde a su comportamiento definido.
❌ No es correcta la lógica de que el líder es quien desafía al oponente; se debería tomar el poder total del gremio al desafiar.
### Punto 3
⚠️ Vuelve a romperse el encapsulamiento al consultarse si un miembro es o no gremio.
❌ No es correcta la lógica implementada; por ej., puede haber casos en los que haya un miembro individual que sea más fuerte que un gremio dentro de la lista de miembros.
## Tests
N/A.

---------------------

Nota: 4

**Comment by franco-creator** [comment]
Buenas profe, le puedo hacer unas consultas del parcial? Que hay algunas
cosas que no entendi, se lo pregunto por aca o por el discord?
